#!/bin/sh
# Auto-generated by generate-server-dashboards.py — do not edit by hand.
set -eu

GRAFANA_URL="${GRAFANA_URL:-http://grafana:3000}"
USER="${GRAFANA_ADMIN_USER:-admin}"
PASS="${GRAFANA_ADMIN_PASSWORD:?Set GRAFANA_ADMIN_PASSWORD}"

auth="--auth-no-challenge --http-user=$USER --http-password=$PASS"

wait_for_grafana() {
  echo "Waiting for Grafana at $GRAFANA_URL ..."
  i=0
  while [ "$i" -lt 60 ]; do
    if wget -q -O- "$GRAFANA_URL/api/health" >/dev/null 2>&1; then
      echo "Grafana is up."
      return 0
    fi
    i=$((i + 1))
    sleep 2
  done
  echo "Grafana did not become healthy in time." >&2
  exit 1
}

upsert_folder() {
  uid=$1
  title=$2
  parent=$3
  if [ -n "$parent" ]; then
    body=$(printf '{"uid":"%s","title":"%s","parentUid":"%s"}' "$uid" "$title" "$parent")
  else
    body=$(printf '{"uid":"%s","title":"%s"}' "$uid" "$title")
  fi
  if wget -q -O- $auth "$GRAFANA_URL/api/folders/$uid" >/dev/null 2>&1; then
    wget -q -O- $auth --method=PUT --header="Content-Type: application/json" \
      --body-data="$body" "$GRAFANA_URL/api/folders/$uid" >/dev/null
    echo "Updated folder $title ($uid)"
  else
    if wget -q -O- $auth --method=POST --header="Content-Type: application/json" \
        --body-data="$body" "$GRAFANA_URL/api/folders" >/dev/null 2>&1; then
      echo "Created folder $title ($uid)"
    else
      echo "Folder $title ($uid) already exists or could not be created."
    fi
  fi
}

if [ "${GRAFANA_SKIP_WAIT:-0}" != "1" ]; then
  wait_for_grafana
fi
upsert_folder "servers" "Servers" ""
upsert_folder "servers-comparison" "Comparison" "servers"
upsert_folder "servers-manager" "Manager" "servers"
upsert_folder "servers-pms-api" "PMS API" "servers"
upsert_folder "servers-receiver" "Receiver" "servers"
upsert_folder "servers-scraper" "Scraper" "servers"
upsert_folder "servers-worker" "Worker" "servers"

reload_dashboards() {
  echo "Reloading dashboard provisioning..."
  wget -q -O- $auth --method=POST \
    "$GRAFANA_URL/api/admin/provisioning/dashboards/reload"
}
reload_dashboards

